In [1]:
import tensorflow as tf

In [13]:
sess = tf.InteractiveSession()

In [43]:
x = tf.constant([[1,2,3,4]]*7, tf.float32)
y = tf.truncated_normal(x.shape)
z = x + y
mean, var = tf.nn.moments(z, 0)
print(z.eval())
print('mean=', mean.eval(), '\nvar=',var.eval())

[[ 1.41028273  1.76107073  2.1326015   3.25804257]
 [-0.29294467  1.32900047  3.68154383  3.18772244]
 [-0.45015633  1.11059964  3.40281439  3.56811571]
 [ 0.69193411  1.46399367  3.12278247  4.01428461]
 [ 1.87994528  1.89346516  1.92173779  2.68355751]
 [ 2.22133255  3.30972195  3.50474811  4.51246405]
 [ 1.25771391  0.31267393  2.96506882  4.30967855]]
mean= [ 0.69804859  1.60123134  3.57658982  4.10836506] 
var= [ 1.01954579  1.23900151  0.58759832  0.73256236]


In [44]:
w = tf.nn.batch_normalization(z,mean,var,0,1,1e-4)
mean, var = tf.nn.moments(w, 0)
print(w.eval())
print('mean=', mean.eval(), '\nvar=',var.eval())

[[ 1.53355587  0.38661456  0.10948229  1.430058  ]
 [-0.27069056  0.80823851 -0.27680206 -1.31970453]
 [ 0.63089526 -1.77756488  1.54642105  0.50779915]
 [ 0.92064953 -0.56752062  0.82397366  0.3272028 ]
 [-1.43046248 -0.67386436 -1.86051989  0.67843962]
 [-0.28913945  1.45824242 -0.56958675 -0.08079386]
 [-1.09480834  0.36585569  0.22702885 -1.54300475]]
mean= [ -2.55448480e-08   1.70298989e-07  -3.40597985e-08  -2.04358784e-07] 
var= [ 0.99983579  0.99980336  0.99982071  0.99983197]
